linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - goconst
    - gocyclo
    - goimports
    - misspell
    - unparam
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0.8
  goconst:
    min-len: 3
    min-occurrences: 3

run:
  deadline: 1m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 